source "https://rubygems.org"

ruby "3.1.7"

gem "jekyll", "~> 4.4.1"

# Fix sass-embedded issue on GitHub Actions Ubuntu 24.04
gem "sass-embedded", "1.77.8"

# Windows support
platforms :mingw, :x64_mingw, :mswin do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
  gem "wdm", "~> 0.1.1"
end

# Required for Jekyll on Ruby 3+
gem "webrick", "~> 1.8"

# GitHub Pages compatibility
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
  gem "jekyll-seo-tag"
  gem "jekyll-remote-theme"
  gem "jekyll-include-cache"
end
