source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"
gem "jekyll-feed", "~> 0.17"

# Fix GitHub Actions sass issue
gem "sass-embedded", "1.77.8"

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", platforms: [:mingw, :x64_mingw, :mswin]

gem "http_parser.rb", "~> 0.6.0"

gem "webrick", "~> 1.8"
